contacts/urls.py
from django.urls import path, include

from .views import *


urlpatterns = [
    path('', ContactsHome.as_view(), name='home'),
    path('add_contact/', create_contact, name='add_contact'),
    path('show_bdays/', ContactsBirthday.as_view(), name='show_bdays'),
    path('contact/delete/<slug:slug>', ContactDelete.as_view(), name='contact_delete'),
    path('contact/edit/<slug:slug>', personal_info_update, name='personal_info_edit'),
    path('contact/phone/edit/<slug:contact_slug>', phone_update, name='phone_edit'),
    path('contact/email/edit/<slug:contact_slug>', email_update, name='email_edit'),
    path('export/', export_contacts, name='export_contacts'),
    path('import/',import_contacts, name='import_contacts'),
    path('search/', SearchContacts.as_view(), name='search')
]

users/urls.py
from django.contrib.auth.views import (
    LogoutView,
    LoginView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path

from . import views
from .forms import LoginForm
from .views import *


urlpatterns = [
    path("signup/", RegisterUser.as_view(), name="register"),
    path("signin/", CustomLoginView.as_view(),name="login",),
    path("logout/",logout_user, name="logout"),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path("reset-password/complete/", CustomPasswordResetCompleteView.as_view(), name="password_reset_complete",),
    path("profile/me",profile, name="profile"),
]

virtassis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from contacts.views import *
from virtassis import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("additional_app.urls")),
    path('files/', include('filemanager.urls')),
    path('contacts/', include('contacts.urls')),
    path('users/', include('users.urls')),
    path('notes/', include('noteapp.urls')),
]

if settings.DEBUG:
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

filemanager/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class File(models.Model):
    CATEGORIES = (
        ('images', 'Images'),
        ('documents', 'Documents'),
        ('videos', 'Videos'),
        ('others', 'Others'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    file = models.FileField(upload_to='files/')
    category = models.CharField(max_length=20, choices=CATEGORIES)
    upload_datetime = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

contacts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelMultipleChoiceField, CheckboxSelectMultiple, BaseInlineFormSet

from .models import *


class AddContactForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["gender"].empty_label = "None"

    class Meta:
        model = Contact
        fields = ["first_name", "last_name", "birthdate", "gender", "address", "photo", ]
        labels = {
            'first_name': 'First name*',
            'last_name': 'Last name*',
            'gender': 'Gender*',
            }
        widgets = {
            "address": forms.Textarea(
                attrs={"cols": 30, "rows": 5},
            ),
            "birthdate": forms.DateInput(attrs={'placeholder': 'YYYY-mm-dd'})
        }

class AddPhoneForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["phone"].required = False
        self.fields["field_type"].required = False
        self.fields["field_type"].empty_label = "None"

    class Meta:
        model = PhoneNumber
        fields = ["phone", "field_type",]
        widgets = {"phone": forms.TextInput(attrs={'placeholder': 'only digits here'})
        }


class AddEmailForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["email"].required = False
        self.fields["field_type"].required = False
        self.fields["field_type"].empty_label = "None"

    class Meta:
        model = Email
        fields = ["email", "field_type"]


class ContactImportForm(forms.Form):
        csv_file = forms.FileField(label='CSV file')

        class Meta:
            fields = ['csv_file',]


class EmailFormSet(BaseInlineFormSet):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for form in self.forms:
            form.fields.pop('contact')


class PhoneFormSet(BaseInlineFormSet):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for form in self.forms:
            form.fields.pop('contact')

contacts/views.py
import csv
import re
from datetime import date, timedelta, datetime

from dateutil.parser import parse
from django import forms
from django.shortcuts import get_object_or_404, render, redirect
from django.http import (
    Http404,
    HttpResponse,
    HttpResponseNotFound,
    HttpResponseRedirect,
)
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    DeleteView,
    UpdateView,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse_lazy
from django.shortcuts import render
from django.db.models import Q
from django.core.paginator import Paginator
from django.utils import timezone
from django.core.exceptions import ValidationError


from .utils import DataMixin, menu, apps
from .models import *
from .forms import *


class ContactsHome(LoginRequiredMixin, DataMixin, ListView):
    model = Contact
    template_name = "contacts/index.html"
    context_object_name = "contacts"

    class DaysForm(forms.Form):
        days = forms.IntegerField(label="Number of Days")

    def get_context_data(self, *, object_list=None, **kwargs):
        request = self.request
        context = super().get_context_data(**kwargs)
        form = self.DaysForm(request.GET)
        days = request.GET.get("days") or 7

        c_def = self.get_user_context(
            title="Contacts",
        )

        return dict(list(context.items()) + list(c_def.items()))

    def get_queryset(self):
        user = self.request.user
        return Contact.objects.filter(user_id=user.id)


class ContactsBirthday(LoginRequiredMixin, DataMixin, ListView):
    model = Contact
    template_name = "contacts/upcoming_birthdays.html"
    context_object_name = "contacts"

    class DaysForm(forms.Form):
        days = forms.IntegerField(label="")

    def get_queryset(self):
        user = self.request.user
        queryset = super().get_queryset().filter(user=user)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        request = self.request
        context = super().get_context_data(**kwargs)

        form = self.DaysForm(request.GET or None)
        days = request.GET.get("days") or 7

        today = date.today()
        end_date = today + timedelta(days=int(days))
        start_date = today

        verified_contacts = []
        contacts = self.get_queryset()
        for c in contacts:
            if c.birthdate:
                contact_birthdate = c.birthdate.date()
                contact_birthdate = contact_birthdate.replace(year=today.year)
                if start_date <= contact_birthdate <= end_date:
                    verified_contacts.append(c)

        c_def = self.get_user_context(
            title="Birthdays",
        )
        context["form"] = form
        context["contacts"] = verified_contacts

        return dict(list(context.items()) + list(c_def.items()))

def validate_phone_number(phone_number):
    phone_number = phone_number
    
    if len(phone_number) not in range(10, 13): 
        return False
    
    if not phone_number.isdigit():
        return False
    
    return True

@login_required
def create_contact(request):
    if request.method == "POST":
        contact_form = AddContactForm(request.POST, request.FILES, prefix="contact")
        phone_number_forms = [
            AddPhoneForm(request.POST, prefix=f"phone_{i}") for i in range(0, 2)
        ]
        email_form = AddEmailForm(request.POST, prefix="email")

        context = {
        "contact_form": contact_form,
        "phone_number_forms": phone_number_forms,
        "email_form": email_form,
        "menu": menu,
        "apps": apps,
        "title": "Add Contact",
    }

        if (
            contact_form.is_valid()
            and email_form.is_valid()
            and all(form.is_valid() for form in phone_number_forms)
        ):
            contact = contact_form.save(commit=False)
            contact.user_id = request.user.id if request.user.is_authenticated else None

            
            existing_contacts = Contact.objects.filter(user_id=request.user.id).all()
            similar_contacts = []
            for _ in existing_contacts:
                clean_last_name = _.last_name.split("(")
                
                if contact_form.cleaned_data['first_name'] == _.first_name and contact_form.cleaned_data['last_name'] == clean_last_name[0].strip():
                    similar_contacts.append(_)
            if similar_contacts:
                contact.last_name = f"{contact_form.cleaned_data['last_name']} ({len(similar_contacts)})"
            
            contact.save()

            email = email_form.save(commit=False)
            email.contact = contact
            email.save()

            for form in phone_number_forms:
                if form.cleaned_data['phone'] != '':
                    phone_number = form.save(commit=False)
                    phone_number.contact = contact
                    if phone_number:
                        if not validate_phone_number(phone_number.phone):
                            form.add_error('phone', 'Invalid phone number')
                            context = {
            "contact_form": contact_form,
            "phone_number_forms": phone_number_forms,
            "email_form": email_form,
            "menu": menu,
            "apps": apps,
            "title": "Add Contact",
        }

                            return render(request, "contacts/add_contact.html", context)
                        
                        phone_number.save()
                        
            full_name = f"{contact_form.cleaned_data['first_name']} {contact_form.cleaned_data['last_name']}"
            messages.success(request, f"Contact {full_name} was added!")
            return redirect("home")
    else:
        contact_form = AddContactForm(prefix="contact")
        phone_number_forms = [AddPhoneForm(prefix=f"phone_{i}") for i in range(0, 2)]
        email_form = AddEmailForm(request.POST, prefix="email")

    context = {
        "contact_form": contact_form,
        "phone_number_forms": phone_number_forms,
        "email_form": email_form,
        "menu": menu,
        "apps": apps,
        "title": "Add Contact",
    }
    return render(request, "contacts/add_contact.html", context)


class ContactDelete(LoginRequiredMixin, DataMixin, DeleteView):
    model = Contact
    success_url = reverse_lazy("home")
    template_name = "contacts/contact_delete.html"

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if obj.user != self.request.user:
            raise Http404("Contact does not exist.")
        return obj

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.delete()
        messages.success(request, "Contact was deleted!")
        return self.get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Delete contact")
        return dict(list(context.items()) + list(c_def.items()))


@login_required
def personal_info_update(request, slug):
    contact = Contact.objects.get(slug=slug)

    if request.method == "POST":
        form = AddContactForm(request.POST, request.FILES, instance=contact)

        if form.is_valid():
            form.save()
            messages.success(
                request,
                f"{contact.first_name}'s personal information was updated successfully!",
            )
            return redirect("home")
    else:
        form = AddContactForm(instance=contact)

    context = {
        "contact": contact,
        "form": form,
        "title": "Edit Contact's info",
        "menu": menu,
    }

    return render(request, "contacts/contact_edit.html", context)


@login_required
def phone_update(request, contact_slug):
    contact = Contact.objects.get(slug=contact_slug)
    FormSet = forms.inlineformset_factory(
        Contact, PhoneNumber, form=AddPhoneForm, formset=PhoneFormSet, extra=1, can_delete=True
    )

    if request.method == "POST":
        phone_formset = FormSet(request.POST, instance=contact, prefix="phone")

        context = {
            "contact": contact,
            "phone_formset": phone_formset,
            "menu": menu,
            "apps": apps,
            "title": "Add Contact",
    }

        if phone_formset.is_valid():
            for form in phone_formset:
                if not validate_phone_number(form.cleaned_data["phone"]):
                    form.add_error('phone', 'Invalid phone number')
                    return render(request, "contacts/phone_edit.html", context)


                phone_formset.save()
                messages.success(
                    request, f"{contact.first_name}'s phones were updated successfully!"
                )
                return redirect("home")
    else:
        phone_formset = FormSet(instance=contact, prefix="phone")

    context = {
        "menu": menu,
        "title": "Edit Phones",
        "contact": contact,
        "phone_formset": phone_formset,
    }

    return render(request, "contacts/phone_edit.html", context)


@login_required
def email_update(request, contact_slug):
    contact = Contact.objects.get(slug=contact_slug)
    FormSet = forms.inlineformset_factory(Contact, Email, form=AddEmailForm, formset=EmailFormSet, extra=1, can_delete=True)

contacts/templates/contacts/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <title>{{title}}</title>
    <link type="text/css" href="{% static 'contacts/css/styles.css' %}" rel="stylesheet" />
    <link type="text/css" href="{% static 'users/css/styles.css' %}" rel="stylesheet" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="shortcut icon" href="{% static 'contacts/images/main.ico' %}" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>

<body>
    <table class="table-page" border=0 cellpadding="0" cellspacing="0">
        <tr>
            <td valign=top>

                {% block mainmenu %}
                <div class="header">
                    <ul id="mainmenu" class="mainmenu">
                        <li class="logo"><a href="{% url 'main' %}">
                                <div class="logo"></div>
                            </a></li>
                        {% for m in menu %}
                        <li><a href="{% url m.url_name %}">{{m.title}}</a></li>
                        {% endfor %}
                        {% if request.user.is_authenticated %}
                        <li class="last">

                            Welcome, <a
                            href="{% url 'profile' %}"><span style="font-size: 20px; font-weight: bold;">{{ user.username }}</span></a> | <a
                                href="{% url 'logout' %}"><button type="button"
                                    class="btn btn-danger btn-sm">Logout</button></a>
                        <li class="user-button__image"></li>
                        </li>
                        {% else %}
                        <li class="last">
                            <a href="{% url 'register' %}"><button type="button" class="btn btn-danger"><i
                                        class="bi bi-star me-1"></i>Register</button></a>
                            <a href="{% url 'login' %}" /><button type="button"
                                class="btn btn-dark">Login</button></a>
                        </li>
                        {% endif %}
                    </ul>
                    <div class="clear"></div>
                </div>
                {% endblock mainmenu %}

                <table class="table-content" border=0 cellpadding="0" cellspacing="0">
                    <tr>
                        <!-- Sidebar left -->

                        <td valign="top" class="left-chapters">
                            <ul id="leftchapters">
                                {% if request.user.is_authenticated %}
                                {% if title == 'Contacts' %}
                                <li class="selected"><span class="glyphicon glyphicon-book"></span> Contacts</li>
                                {% else %}
                                <li style="font-size: 25px; "><a href="{% url 'home' %}"><span class="glyphicon glyphicon-book"></span> Contacts</a></li>
                                {% endif %}
                                {% if title == 'Notes' %}
                                <li class="selected"><span class="glyphicon glyphicon-pushpin"></span> Notes</li>
                                {% else %}
                                <li style="font-size: 25px; "><a href="{% url 'notes' %}"><span class="glyphicon glyphicon-pushpin"></span> Notes</a></li>
                                {% endif %}
                                {% if title == 'File List' %}
                                <li class="selected"><span class="glyphicon glyphicon-folder-open"></span> Files</li>
                                {% if title == 'File List' or title == 'Upload File' %}
                                <div>_________________</div>
                                <div><a href="{% url 'file_list' %}"><span
                                            class="badge border-light border-1 text-black-50">All</a></span></div>
                                <div><a href="{% url 'file_list' %}?category=images"><span
                                            class="badge border-light border-1 text-black-50">Images</a></span></div>
                                <div><a href="{% url 'file_list' %}?category=documents"><span
                                            class="badge border-light border-1 text-black-50">Documents</a></span></div>
                                <div><a href="{% url 'file_list' %}?category=videos"><span
                                            class="badge border-light border-1 text-black-50">Videos</a></span></div>
                                <div><a href="{% url 'file_list' %}?category=others"><span class="badge border-light border-1 text-black-50">Others</a></span></div>
                                <div>_________________</div>
                                {% endif %}
                                {% else %}
                                <li style="font-size: 25px; "><a href="{% url 'file_list' %}"><span class="glyphicon glyphicon-folder-open"></span> Files</a></li>
                                {% endif %}
                                {% if title == 'Home' %}
                                <li class="selected"><span class="glyphicon glyphicon-globe"></span> News</li>
                                {% else %}
                                <li style="font-size: 25px; "><a href="{% url 'main' %}"><span class="glyphicon glyphicon-globe"></span> News</a></li>
                                {% endif %}
                            </ul>
                        </td>
                        {% else %}
                        {% if title == 'Login' or title == 'Signup' or title == 'Password reset' or title == 'Password reset sent' or title == 'Password reset complete' or title == 'Enter new password' or title == 'Password reset successful' or title == 'Password reset unsuccessful'%} 
                        <li style="font-size: 25px; "><a href="{% url 'main' %}"><span class="glyphicon glyphicon-globe"></span> News</a></li>
                        {% else %}
                        <li class="selected"><span class="glyphicon glyphicon-globe"> </span>News</li>
                        {% endif %}
                        {% endif %}
                        <!-- End Sidebar's -->
                        {% if title == 'Login' or title == 'Signup' %}
                        <td valign="top" class="content back">
                            <div class="content-text">
                                {% else %}
                        <td valign="top" class="content">
                            <div class="content-text">
                                {% endif %}
                                {% block content %}
                                {% endblock %}
                            </div>
                            </div>
                        </td>

            </td>
        </tr>
    </table>
    </td>
    </tr>
    <!-- Footer -->
        <div>
            <td valign=top>
                <div id="footer">
                    <p>Powered by Django Dreams Co. &copy; 2023 All rights reserved</p>
                </div>
            </td>
            </div>
        </div>
    </table>

</body>

</html>

contacts/templates/contacts/contact_delete.html
{% extends 'contacts/base.html' %}

{% block content %}
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

<h1>Delete Contact</h1>
<p>Are you sure you want to delete <strong>{{contact.first_name}} {{contact.last_name}}</strong> contact?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete</button>
    <a href="{% url 'home' %}" class="btn btn-secondary">Cancel</a>
</form>
<style>
    body {
        margin: 0;
        padding: 0;
        background-color: #acaaa7;
        /* Replace with your desired color */
    }
</style>
{% endblock %}

contacts/templates/contacts/index.html
{% extends 'contacts/base.html' %}

{% block content %}
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
{% if messages %}
{% for msg in messages %}
<div class="alert {%if msg.tags %} alert-{{msg.tags}} {% endif %}" role="alert">{{msg}}</div>
{% endfor %}
{% endif %}

<div>
    <div class="fit2">
        <h1>Contacts</h1>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <p style="font-size: 24px">Retrieve the contacts' entries who have a birthday in</p>
        </div>
        <div class="col-sm-2">
            <form action="{% url 'show_bdays' %}" method="get">
                <input type="number" name="days" required id="id_days">
        </div>

        <div class="col-sm-1">
            <p style="font-size: 23px">day(s)</p>
        </div>

        <div class="col-sm-2">
            <button type="submit" class="btn btn-success">Go!</button>
        </div>
        </form>
    </div>
    <div class="fit">
        <div class="row">
            <div class="col-sm-2">
                <a href="{% url 'add_contact' %}"><button type="submit" class="btn btn-success rounded-pill">+
                        Add</button></a>
            </div>
            <div class="col-sm-2">
                <a href="{% url 'import_contacts' %}"><button type="submit" class="btn btn-success rounded-pill">+
                        Import
                        .csv</button></a>
            </div>
            <div class="col-sm-2">
                <a href="{% url 'export_contacts' %}"><button type="submit" class="btn btn-primary rounded-pill">+
                        Export
                        .csv</button></a>
            </div>
            <form action="{% url 'search' %}" method="get" class="col-sm-5 d-flex mt-3 mt-lg-0" role="search">
                <input class="form-control me-2" type="search" name="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</div>
<div>

    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">Photo</th>
                <th scope="col">Name</th>
                <th scope="col">Last name</th>
                <th scope="col">Birthdate</th>
                <th scope="col">Phones</th>
                <th scope="col">Email</th>
                <th scope="col">Gender</th>
                <th scope="col">Address</th>
                <th scope="col" style="padding-left: 48px;">Edit</th>
                <th scope="col">Delete</th>
            </tr>
        </thead>
        {% for contact in contacts %}
        <tbody>
            <tr>
                {% if contact.photo %}
                <td><img src="{{contact.photo.url}}" width="64" height="64"></td>
                {% else %}
                {% if contact.gender == 'male' %}
                <td>
                    <p class="pic_m"></p>
                </td>
                {% else %}
                <td>
                    <p class="pic_f"></p>
                </td>
                {% endif %}
                {% endif %}
                <td style="display: table-cell; vertical-align: middle;">{{ contact.first_name }}</td>
                <td style="display: table-cell; vertical-align: middle;">{{ contact.last_name }}</td>
                <td style="display: table-cell; vertical-align: middle;">{{ contact.birthdate.date }}</td>
                <td style="display: table-cell; vertical-align: middle;">
                    {% for phone in contact.phones.all %}
                    {% if phone.phone %}
                    {{ phone.phone }}{% if phone.field_type %} - {{ phone.field_type }}{% endif %}
                    {% if not forloop.last %}</br>{% endif %}
                    {% endif %}
                    {% endfor %}
                </td>
                <td style="display: table-cell; vertical-align: middle;">
                    {% for email in contact.emails.all %}
                    {% if email.email %}
                    {{ email.email }}{% if email.field_type %} - {{ email.field_type }}{% endif %}
                    {% if not forloop.last %}</br>{% endif %}
                    {% endif %}
                    {% endfor %}
                </td>
                <td style="display: table-cell; vertical-align: middle;">{{ contact.gender }}</td>
                <td style="display: table-cell; vertical-align: middle;">{{ contact.address|slice:":20" }}{% if contact.address|length > 20 %}...{% endif %}</td>
                <td style="display: table-cell; vertical-align: middle;"><a href="{% url 'personal_info_edit' contact.slug %}"><button type="button" class="btn btn-outline-info"><span class="glyphicon glyphicon-user"></span></button></a><a href="{% url 'phone_edit' contact.slug %}"><button type="button" class="btn btn-outline-secondary"><span class="glyphicon glyphicon-phone"></span></button></a><a href="{% url 'email_edit' contact.slug %}"><button type="button" class="btn btn-outline-info"><span class="glyphicon glyphicon-envelope"></span></button></a></td>
                <td style="display: table-cell; vertical-align: middle;"><a href="{% url 'contact_delete' contact.slug %}"><button type="button"
                            class="btn btn-danger rounded-pill">Delete</button></a></td>
            </tr>
        </tbody>
        {% endfor %}
    </table>
</div>
<div>
    <nav class="list-pages">
        {% if page_obj.has_other_pages %}
        <ul>
            {% if page_obj.has_previous %}
            <li>
                <a href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
            </li>
            {% endif %}
            {% if page_obj.number == 4 %}
            <li class="page-num"><a href="?page=1">1</a></li>
            {% endif %}
            {% if page_obj.number > 4 %}
            <li class="page-num"><a href="?page=1">1</a></li>
            <li><span>...</span></li>
            {% endif %}
            {% for p in paginator.page_range %}
            {% if page_obj.number == p %}
            <li class="page-num page-num-selected">{{p}}</li>
            {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %} <li class="page-num">
                <a href="?page={{p}}">{{p}}</a>
                </li>
                {% endif %}
                {% endfor %}
                {% if page_obj.number < page_obj.paginator.num_pages|add:'-3' %} <li>
                    <span>...</span></li>
                    <li class="page-num"><a
                            href="?page={{page_obj.paginator.num_pages}}">{{page_obj.paginator.num_pages}}</a>
                    </li>
                    {% endif %}
                    {% if page_obj.number == page_obj.paginator.num_pages|add:'-3' %}
                    <li class="page-num"><a
                            href="?page={{page_obj.paginator.num_pages}}">{{page_obj.paginator.num_pages}}</a>
                    </li>
                    {% endif %}
                    {% if page_obj.has_next %}
                    <li>
                        <a href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                    </li>
                    {% endif %}
        </ul>
        {% endif %}
    </nav>
</div>
<style>
    body {
        margin: 0;
        padding: 0;
        background-color: #acaaa7;
        /* Replace with your desired color */
    }
</style>
</div>
{% endblock %}